<a href="https://colab.research.google.com/github/saranoor/chatGPT/blob/master/policy_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Load the dataset
We will combine the review summary and review text into a single combined text. The model will encode this combined text and it will output a single vector embedding.

To run this notebook, you will need to install: pandas, openai, transformers, plotly, matplotlib, scikit-learn, torch (transformer dep), torchvision, and scipy.

In [1]:
!pip install tiktoken

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tiktoken
  Downloading tiktoken-0.3.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 19.5 MB/s eta 0:00:00
Collecting requests>=2.26.0
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 6.6 MB/s eta 0:00:00
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.9/dist-packages (from tiktoken) (2022.6.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26.0->tiktoken) (2.10)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 19.0 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26.0->tiktoken) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.26.0->tiktoken) (1.26.14)
Installing collected packages: charset-normalizer, requests, tiktoken
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
Successfully installed charset-normalizer-3.1.0 requests-2.28.2 tiktoken-0.3.1

In [2]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [3]:
pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.26.1-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 41.1 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from transformers) (6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from transformers) (23.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.9/dist-packages (from transformers) (4.65.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from transformers) (2.28.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from transformers) (3.9.0)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 68.9 MB/s eta 0:00:00
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/dist-packages (from transformers) (2022.6.2)
Collecting huggingface-hub<1.0,>=0.11.0
  Downloading huggingface_hub-0.13.1-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 19.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.9/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.11.0->transformers) (4.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->transformers) (1.26.14)
Installing collected packages: tokenizers, huggingface-hub, transformers
Successfully installed huggingface-hub-0.13.1 tokenizers-0.13.2 transformers-4.26.1

In [4]:
pip install plotly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.9/dist-packages (5.5.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from plotly) (8.2.2)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from plotly) (1.15.0)

In [5]:
pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (3.5.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (4.39.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (8.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (3.0.9)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)

In [6]:
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (1.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.2.0)

In [7]:
pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: torch in /usr/local/lib/python3.9/dist-packages (1.13.1+cu116)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from torch) (4.5.0)

In [8]:
!pip install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: torchvision in /usr/local/lib/python3.9/dist-packages (0.14.1+cu116)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.9/dist-packages (from torchvision) (8.4.0)
Requirement already satisfied: torch==1.13.1 in /usr/local/lib/python3.9/dist-packages (from torchvision) (1.13.1+cu116)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from torchvision) (4.5.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from torchvision) (1.22.4)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from torchvision) (2.28.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->torchvision) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->torchvision) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->torchvision) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->torchvision) (2022.12.7)

In [9]:
pip install scipy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /usr/local/lib/python3.9/dist-packages (from scipy) (1.22.4)

In [10]:
 pip install --upgrade pip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pip in /usr/local/lib/python3.9/dist-packages (22.0.4)
Collecting pip
  Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 22.8 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.0.1

In [11]:
!pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting openai
  Downloading openai-0.27.2-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.1/70.1 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.9/dist-packages (from openai) (2.28.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from openai) (4.65.0)
Collecting aiohttp
  Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 18.4 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (2.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (3.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.20->openai) (1.26.14)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->openai) (22.2.0)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 12.1 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 kB 17.5 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 14.8 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Installing collected packages: multidict, frozenlist, async-timeout, yarl, aiosignal, aiohttp, openai
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 frozenlist-1.3.3 multidict-6.0.4 openai-0.27.2 yarl-1.8.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [12]:
# imports
import pandas as pd
import tiktoken

from openai.embeddings_utils import get_embedding

In [13]:
# embedding model parameters
embedding_model = "text-embedding-ada-002"
embedding_encoding = "cl100k_base"  # this the encoding for text-embedding-ada-002
max_tokens = 8000  # the maximum for text-embedding-ada-002 is 8191

In [14]:
input_datapath="/content/10pearls_sections_text_final.xlsx"
df = pd.read_excel(input_datapath)#, index_col=0)
df.head()
# df = df[["Time", "ProductId", "UserId", "Score", "Summary", "Text"]]
df=df[["title", "heading", "content"]]
df = df.dropna()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 144 entries, 0 to 144
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    144 non-null    object
 1   heading  144 non-null    object
 2   content  144 non-null    object
dtypes: object(3)
memory usage: 4.5+ KB

In [16]:
# load & inspect dataset
# input_datapath = "./fine_food_reviews_1k.csv"  # to save space, we provide a pre-filtered dataset
# df = pd.read_csv(input_datapath, index_col=0)
# df = df[["Time", "ProductId", "UserId", "Score", "Summary", "Text"]]

df["combined"] = (
    "Title: " + df.title.str.strip() +"; Heading: " + df.heading.str.strip()+ "; Content: " + df.content.str.strip()
)
df.head(2)

,title,heading,content,combined
0,10Pearls Policies and Procedures,OUR MISSION,TenPearls (Private) Limited is founded on the ...,Title: 10Pearls Policies and Procedures; Headi...
1,Definitions in 10Pearls Policies and Procedures,DEFINITIONS,In this Manual the following words and express...,Title: Definitions in 10Pearls Policies and Pr...

In [17]:
max_tokens

8000

In [18]:
df["n_tokens"].head(10)

KeyError: ignored

In [19]:
# subsample to 1k most recent reviews and remove samples that are too long
top_n = 1000
# df = df.sort_values("Time").tail(top_n * 2)  # first cut to first 2k entries, assuming less than half will be filtered out
# df.drop("Time", axis=1, inplace=True)

encoding = tiktoken.get_encoding(embedding_encoding)

# omit reviews that are too long to embed
df["n_tokens"] = df.combined.apply(lambda x: len(encoding.encode(x)))
# df = df[df.n_tokens <= max_tokens].tail(top_n)
len(df)

144

In [20]:
df[df.n_tokens <= max_tokens]

,title,heading,content,combined,n_tokens
0,10Pearls Policies and Procedures,OUR MISSION,TenPearls (Private) Limited is founded on the ...,Title: 10Pearls Policies and Procedures; Headi...,109
1,Definitions in 10Pearls Policies and Procedures,DEFINITIONS,In this Manual the following words and express...,Title: Definitions in 10Pearls Policies and Pr...,41
2,Definitions in 10Pearls Policies and Procedures,Company,“Company” shall mean TenPearls (Private) Limited;,Title: Definitions in 10Pearls Policies and Pr...,31
3,Definitions in 10Pearls Policies and Procedures,PULSE,“PULSE” shall mean the Company online portal a...,Title: Definitions in 10Pearls Policies and Pr...,37
4,Definitions in 10Pearls Policies and Procedures,Employee,“Employee(s)” shall mean all employees of the ...,Title: Definitions in 10Pearls Policies and Pr...,54
...,...,...,...,...,...
140,APPENDIX J in 10Pearls Policies and Procedures,CEILING AMOUNT,Level\nManagers and Asst. Managers/Architects\...,Title: APPENDIX J in 10Pearls Policies and Pro...,88
141,APPENDIX K in 10Pearls Policies and Procedures,PURPOSE,The Company has designed LTIP to reward its el...,Title: APPENDIX K in 10Pearls Policies and Pro...,120
142,APPENDIX K in 10Pearls Policies and Procedures,PARTICIPANTS FOR THE LTIP UNITS,• The officers and other senior executive Conf...,Title: APPENDIX K in 10Pearls Policies and Pro...,528
143,APPENDIX K in 10Pearls Policies and Procedures,MINIMUM HOLDING PERIOD AND ACTUAL HOLDING PERIOD,The Minimum Holding Period for LTIP Units issu...,Title: APPENDIX K in 10Pearls Policies and Pro...,333
144,APPENDIX K in 10Pearls Policies and Procedures,EMPLOYEE ACKNOLWEDGMENT,It is the responsibility of all Employees to r...,Title: APPENDIX K in 10Pearls Policies and Pro...,83

## 2. Get embeddings and save them for future reuse

In [ ]:
import openai
openai.api_key=''

In [ ]:
df.loc[0:40]

,title,heading,content,combined,n_tokens
0,10Pearls Policies and Procedures,OUR MISSION,TenPearls (Private) Limited is founded on the ...,Title: 10Pearls Policies and Procedures; Headi...,106
1,Definitions in 10Pearls Policies and Procedures,DEFINITIONS,In this Manual the following words and express...,Title: Definitions in 10Pearls Policies and Pr...,39
2,Definitions in 10Pearls Policies and Procedures,Company,“Company” shall mean TenPearls (Private) Limited;,Title: Definitions in 10Pearls Policies and Pr...,28
3,Definitions in 10Pearls Policies and Procedures,PULSE,“PULSE” shall mean the Company online portal a...,Title: Definitions in 10Pearls Policies and Pr...,34
4,Definitions in 10Pearls Policies and Procedures,Employee,“Employee(s)” shall mean all employees of the ...,Title: Definitions in 10Pearls Policies and Pr...,51
5,Definitions in 10Pearls Policies and Procedures,Full-Time Employee,“Full-Time Employee(s)” shall mean Employee(s)...,Title: Definitions in 10Pearls Policies and Pr...,48
6,Definitions in 10Pearls Policies and Procedures,Fixed Term Contractual Employee,“Fixed Term Contractual Employee(s)” shall mea...,Title: Definitions in 10Pearls Policies and Pr...,48
7,Definitions in 10Pearls Policies and Procedures,HR,“HR” shall mean the Human Resource Department ...,Title: Definitions in 10Pearls Policies and Pr...,28
8,Definitions in 10Pearls Policies and Procedures,Half Day,“Half Day” shall mean at least four and a half...,Title: Definitions in 10Pearls Policies and Pr...,43
9,Definitions in 10Pearls Policies and Procedures,Interns,“Interns” shall mean person(s) engaged for wor...,Title: Definitions in 10Pearls Policies and Pr...,43
10,Definitions in 10Pearls Policies and Procedures,Long Leave,“Long Leave” shall mean leave of three or more...,Title: Definitions in 10Pearls Policies and Pr...,29
11,Definitions in 10Pearls Policies and Procedures,Part-Time Employee,“Part- Time Employee(s)” shall mean Employee(s...,Title: Definitions in 10Pearls Policies and Pr...,44
12,Definitions in 10Pearls Policies and Procedures,Monetary Benefits,“Monetary Benefits” shall mean the benefits de...,Title: Definitions in 10Pearls Policies and Pr...,37
13,Definitions in 10Pearls Policies and Procedures,Non-Monetary Benefits,“Non-Monetary Benefits” shall mean the benefit...,Title: Definitions in 10Pearls Policies and Pr...,42
14,Definitions in 10Pearls Policies and Procedures,Short Leave,“Short Leave” shall mean leave for a maximum o...,Title: Definitions in 10Pearls Policies and Pr...,33
15,Definitions in 10Pearls Policies and Procedures,Other Benefits and facilities,“Other Benefits and facilities” shall mean the...,Title: Definitions in 10Pearls Policies and Pr...,40
16,Definitions in 10Pearls Policies and Procedures,Associate,“Associate” shall mean graduates with less tha...,Title: Definitions in 10Pearls Policies and Pr...,45
17,General in 10Pearls Policies and Procedures,GENERAL,This Manual is designed to serve as the basic ...,Title: General in 10Pearls Policies and Proced...,52
18,General in 10Pearls Policies and Procedures,EFFECTIVE DATE,"Except otherwise specifically mentioned, the p...",Title: General in 10Pearls Policies and Proced...,82
19,General in 10Pearls Policies and Procedures,APPLICATION,Every Employee of the Company shall be subject...,Title: General in 10Pearls Policies and Proced...,124
20,Duties and Responsibilities in 10Pearls Polici...,Duties and Responsibilities,The following duties are expected to be perfor...,Title: Duties and Responsibilities in 10Pearls...,211
21,Duties and Responsibilities in 10Pearls Polici...,CONFIDENTIALITY,Every Employee is required to observe strict s...,Title: Duties and Responsibilities in 10Pearls...,113
22,Duties and Responsibilities in 10Pearls Polici...,NON-COMPETE,Whilst in the employment of the Company whethe...,Title: Duties and Responsibilities in 10Pearls...,113
23,Employment Associations with TenPearls in 10Pe...,DRESS CODE AND PERSONAL GROOMING,Recommended outfit includes formal shirt and t...,Title: Employment Associations with TenPearls ...,102
24,Employment Associations with TenPearls in 10Pe...,EMPLOYMENT ASSOCIATIONS,Employees may be employed by the Company as ei...,Title: Employment Associations with TenPearls ...,60
25,Employment Associations with TenPearls in 10Pe...,FULL - TIME EMPLOYEES,An Employee will be categorized as Full-time w...,Title: Employment Associations with TenPearls ...,93
26,Employment Associations with TenPearls in 10Pe...,PART-TIME EMPLOYEES,Part-time Employees are those Employees who ar...,Title: Employment Associations with TenPearls ...,101
27,Employment Associations with TenPearls in 10Pe...,FIXED TERM CONTRACTUAL EMPLOYEES,Fixed Term Contractual Employees are under a c...,Title: Employment Associations with TenPearls ...,108
28,Employment Associations with TenPearls in 10Pe...,INTERNS,Interns are engaged for work to gain experienc...,Title: Employment Associations with TenPearls ...,124
29,Employment Associations with TenPearls in 10Pe...,ASSOCIATES,Graduates with less than one year’s experience...,Title: Employment Associations with TenPearls ...,112
30,JOINING THE COMPANY with TenPearls in 10Pearls...,JOINING THE COMPANY,"On joining the company, the Employee must prov...",Title: JOINING THE COMPANY with TenPearls in 1...,275
32,APPOINTMENT & PROBATION in 10Pearls Policies a...,NEW EMPLOYEES,"All newly appointed Employees, except Interns ...",Title: APPOINTMENT & PROBATION in 10Pearls Pol...,156
33,APPOINTMENT & PROBATION in 10Pearls Policies a...,CONFIRMATION,"The Company may, at its sole discretion, confi...",Title: APPOINTMENT & PROBATION in 10Pearls Pol...,139
34,APPOINTMENT & PROBATION in 10Pearls Policies a...,CONFIRMED EMPLOYEES,Upon successful completion of probation period...,Title: APPOINTMENT & PROBATION in 10Pearls Pol...,141
35,MONETARY AND NON-MONETARY BENEFITS in 10Pearls...,MONETARY AND NON-MONETARY BENEFITS,The Company offers various Monetary and Non-Mo...,Title: MONETARY AND NON-MONETARY BENEFITS in 1...,107
36,MONETARY AND NON-MONETARY BENEFITS in 10Pearls...,PROVIDENT FUND,The company has a provident fund scheme throug...,Title: MONETARY AND NON-MONETARY BENEFITS in 1...,135
37,MONETARY AND NON-MONETARY BENEFITS in 10Pearls...,BONUS/INCENTIVE,"Depending upon the revenue generated, the Comp...",Title: MONETARY AND NON-MONETARY BENEFITS in 1...,203
38,MONETARY AND NON-MONETARY BENEFITS in 10Pearls...,OPD,"Upon appointment, all Full-Time Employees are ...",Title: MONETARY AND NON-MONETARY BENEFITS in 1...,152
39,MONETARY AND NON-MONETARY BENEFITS in 10Pearls...,TRANSPORT ALLOWANCE,"Upon appointment, all Full-Time night shift Em...",Title: MONETARY AND NON-MONETARY BENEFITS in 1...,56
40,MONETARY AND NON-MONETARY BENEFITS in 10Pearls...,LOAN,All Full-Time Employees can take a loan that c...,Title: MONETARY AND NON-MONETARY BENEFITS in 1...,72

In [ ]:
df.loc[0:30, 'embeddings']=0

In [ ]:
df.loc[0:30, 'embeddings']=df[0:30].combined.apply(lambda x: get_embedding(x, engine=embedding_model))

In [ ]:
df.loc[30:60, 'embeddings']=df[30:60].combined.apply(lambda x: get_embedding(x, engine=embedding_model))

In [ ]:
df.loc[60:90, 'embeddings']=df[60:90].combined.apply(lambda x: get_embedding(x, engine=embedding_model))

In [ ]:
df.loc[90:120, 'embeddings']=df[90:120].combined.apply(lambda x: get_embedding(x, engine=embedding_model))

In [ ]:
df.loc[120:, 'embeddings']=df[120:].combined.apply(lambda x: get_embedding(x, engine=embedding_model))

In [ ]:
output_datapath="/content/10pearls_sections_text_embeddings.xlsx"

In [ ]:
df.to_excel(output_datapath)

In [ ]:
for i in range(0, 145, 20):
  df.loc[i:i+20, 'embeddings']=df[i:i+20].combined.apply(lambda x: get_embedding(x, engine=embedding_model))
  #df.to_csv("data/fine_food_reviews_with_embeddings_1k.csv")

RetryError: ignored